# Example GitHub Action to scan a Docker image
# See https://github.com/mondoohq/actions/tree/main/docker-image for additional usage information.

name: mondoo-cnspec-scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Scan with cnspec
        uses: mondoohq/actions/docker-image@main
        with:
          service-account-credentials: ${{ secrets.MONDOO_CONFIG_BASE64 }}
          image: ubuntu:22.04
